typography_spectrum: 0.21929647191427648
color:
  brandStrength: 0.8298741825856268
  lightness: 0.5172988751437515
  saturation: 0.9347030476201326
  rhythmicContrast: 0.645967016229406
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.502723386278376
author:
  name: Alex
  email: lwclsvln@gmail.com
name: Low class Villain Productions
navigation:
  - name: FB
    url: 'https://www.facebook.com/lowclassvillain/'
    type: external
  - name: Instagram
    url: 'https://www.instagram.com/lwclsvlnprod/'
    type: external
title: Oil+Digital Paintings
description: Alex Charlebois / Artist
